name: Build and Run on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  run_samples_pc:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Bash script
        shell: bash
        run: |
          cd utilities
          if ! ./run_samples.sh --nogpu --visbuildonly --log-file windows_selftests.log; then
            echo "==== run_samples.sh failed; dumping windows_selftests.log ===="
            cat windows_selftests.log
            exit 1
          fi
